name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/roast-my-playlist:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ECS_PRIVATE_KEY }}

    - name: Deploy to ECS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.ECS_USER }}@${{ vars.ECS_HOST }} << 'EOF'
          sudo docker pull ${{ vars.DOCKERHUB_USERNAME }}/roast-my-playlist:latest
          sudo docker stop ${{ vars.CONTAINER_NAME }} || true
          sudo docker rm ${{ vars.CONTAINER_NAME }} || true
          sudo docker run -d -p ${{ vars.EXPOSED_PORT }}:${{ vars.EXPOSED_PORT }} \
          --name ${{ vars.CONTAINER_NAME }} \
          -e ALLOWED_ORIGINS="${{ vars.ALLOWED_ORIGINS }}" \
          -e SPOTIFY_CLIENT_ID=${{ vars.SPOTIFY_CLIENT_ID }} \
          -e SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          -e SPOTIFY_API_URL=${{ vars.SPOTIFY_API_URL }} \
          -e SPOTIFY_AUTH_URL=${{ vars.SPOTIFY_AUTH_URL }} \
          -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e PORT=${{ vars.PORT }} \
          -e REDIS_PORT=${{ vars.REDIS_PORT }} \
          -e REDIS_HOST=${{ vars.REDIS_HOST }} \
          ${{ vars.DOCKERHUB_USERNAME }}/roast-my-playlist:latest
          sudo docker image prune -f
        EOF